---
title: "Maintenance Script Report: Video Compression"
author:
- MARS 2024
- Compressing our video files
date: "`r lubridate::now()`" #This doesn't use !r syntax (like the gagedb param below) because it's not a param. It's evaluated by default.
output: html_document
params:
  database: "mars14_datav2"
  compress: FALSE
---

```{r setup, include=FALSE}
#Database Stuff
library(odbc)
library(tidyverse)
library(lubridate)

#Other stuff
library(knitr)
library(digest)
options(stringsAsFactors=FALSE)


errorCodes <- data.frame(code = 0:6,
  message = c("Execution successful.",
              "Could not connect to MARS. Is the database down?",
              "No filesystem access. Have you opened //pwdoows/oows in the file explorer in the last month?",
              NA, #Write error from TryCatch will be used,
              NA, #Write error from TryCatch will be used
              NA, #Write error from TryCatch will be used
              NA)
            , stringsAsFactors=FALSE)

kill = FALSE
errorCode = 0

log_code <- digest(now()) #Unique ID for the log batches

parseVideoMetadata <- function(raw){
  #print(raw)
  
  #Did we choke on the moov atom?
  mooverror <- str_detect(raw[1], "moov atom not found")
  if(mooverror == TRUE){
    return(data.frame(frame_rate = -1, bit_rate_mbps = -1))
  }
  
  raw_split <- str_split(raw, pattern = "=") %>%
    as.data.frame
  
  
  #print(raw_split)
  colnames(raw_split) <- raw_split[1, ]
  
  metadata <- raw_split[-1, ] %>% 
    mutate(frame_rate = round(eval(parse(text = r_frame_rate))), 
           bit_rate_mbps = as.numeric(bit_rate)/1024/1024) %>%
    select(-r_frame_rate, -bit_rate)
    
  #print(metadata)
  return(metadata)
}

```

```{r Preamble, include = FALSE}
 	#Connect to MARS database using ODBC channel
	marsDBCon <- dbConnect(odbc::odbc(), params$database)

  #################################
  ####Error check - Did we connect?
  #################################
  if(!odbc::dbIsValid(marsDBCon))
  {
    kill = TRUE
    errorCode = 1
  }

  ###Log: Start
  logMessage <- data.frame(date = as.Date(today()), 
                           milestone = 1,
                           exit_code = NA,
                           note = "Checking DB Connection")
  
  dbWriteTable(marsDBCon, DBI::SQL("log.tbl_script_video"), logMessage, append = TRUE, row.names=FALSE)

  #We will look for video files here recursively
  rootFolder <- "//PWDOOWS/OOWS/Watershed Sciences/GSI Monitoring/02 GSI Monitoring Sites"
  
  targetBitrate_mbps = 5  #megabits per second
  targetFormat = ".mp4"   #file container type
  targetFramerate = 30  #frames per second
  targetCodec = "h264"    #video compression algorithm
                          #h.264 is a good one with open-source tools
                          #https://en.wikipedia.org/wiki/Advanced_Video_Coding

```

```{r Break Point 1 - Bad Connection, echo = FALSE, eval = kill}

  knitr::asis_output("# Script Results: Error\n")
  knitr::asis_output(paste("## Error Code:", errorCode, "\n"))
  knitr::asis_output(paste("## Error Message: ", errorCodes$message[errorCode+1]))
  
  ###Log: End
  logMessage <- data.frame(date = as.Date(today()), 
                           milestone = NA,
                           exit_code = errorCode,
                           note = errorCodes$message[errorCode+1])
  
  dbWriteTable(marsDBCon, DBI::SQL("log.tbl_script_video"), logMessage, append = TRUE, row.names=FALSE)
  
  knitr::knit_exit()

```

```{r Section 1 - Finding the video files, include = FALSE}
  ###Log: Finding video files
  logMessage <- data.frame(date = as.Date(today()), 
                           milestone = 2,
                           exit_code = NA,
                           note = "Crawling for video files")
  
  dbWriteTable(marsDBCon, DBI::SQL("log.tbl_script_video"), logMessage, append = TRUE, row.names=FALSE)

  raw_mp4 <- list.files(path = rootFolder,
                         pattern = ".*\\.mp4",
                         full.names = TRUE,
                         recursive = TRUE)

  raw_mov <- list.files(path = rootFolder,
                         pattern = ".*\\.mov",
                         full.names = TRUE,
                         recursive = TRUE)
  
  #################################
  ####Error check - Do we have filesystem access?
  #################################
  if(length(raw_mp4) == 0)
  {
    kill = TRUE
    errorCode = 2
  }

```

```{r Break Point 2 - No filesystem access, echo = FALSE, eval = kill}

  knitr::asis_output("# Script Results: Error\n")
  knitr::asis_output(paste("## Error Code:", errorCode, "\n"))
  knitr::asis_output(paste("## Error Message: ", errorCodes$message[errorCode+1]))
  
  ###Log: End
  logMessage <- data.frame(date = as.Date(today()), 
                           milestone = NA,
                           exit_code = errorCode,
                           note = errorCodes$message[errorCode+1])
  
  dbWriteTable(marsDBCon, DBI::SQL("log.tbl_script_video"), logMessage, append = TRUE, row.names=FALSE)
  
  knitr::knit_exit()

```

```{r Section 2 - Video Metadata}
  ###Log: Video metadata
  logMessage <- data.frame(date = as.Date(today()), 
                           milestone = 3,
                           exit_code = NA,
                           note = "Gathering video metadata")

  dbWriteTable(marsDBCon, DBI::SQL("log.tbl_script_video"), logMessage, append = TRUE, row.names=FALSE)

  
  ffprobe_stub <- "ffprobe -v error -select_streams v:0 -show_entries stream=bit_rate,r_frame_rate -of default=noprint_wrappers=1 \""

  meta_mp4 <- data.frame(frame_rate = NULL, bit_rate_mpbs = NULL)
  meta_mov <- data.frame(frame_rate = NULL, bit_rate_mbps = NULL)

for(i in 1:length(raw_mp4)){
    ffprobe <- paste0(ffprobe_stub, raw_mp4[i], '\"')
    raw_meta <- system(command = ffprobe, intern = TRUE)

    meta_mp4 <- bind_rows(meta_mp4, parseVideoMetadata(raw_meta))
  }
  
for(i in 1:length(raw_mov)){
    ffprobe <- paste0(ffprobe_stub, raw_mov[i], '\"')
    raw_meta <- system(command = ffprobe, intern = TRUE)
    
    meta_mov <- bind_rows(meta_mov, parseVideoMetadata(raw_meta))
  }
  
  files_mp4 <- data.frame(filepath = raw_mp4) %>%
    cbind(meta_mp4)
  
  files_mov <- data.frame(filepath = raw_mov) %>%
    cbind(meta_mov)
  
```

```{r Section 3 - Prepare to compress}

  ###Log: Video metadata
  logMessage <- data.frame(date = as.Date(today()), 
                           milestone = 4,
                           exit_code = NA,
                           note = "Gathering video metadata")

  dbWriteTable(marsDBCon, DBI::SQL("log.tbl_script_video"), logMessage, append = TRUE, row.names=FALSE)


  check_mp4 <- mutate(files_mp4, 
                      resample = frame_rate > (targetFramerate + 1),
                      compress = bit_rate_mbps > (targetBitrate_mbps + 0.5)) %>%
    rowwise() %>%
    mutate(convert = any(resample, compress))

  check_mov <- mutate(files_mov, 
                      resample = frame_rate > (targetFramerate + 1),
                      compress = bit_rate_mbps > (targetBitrate_mbps + 0.5)) %>%
    rowwise() %>%
    mutate(convert = any(resample, compress))

```

```{r Section 4 - Compose ffmpeg strings}
  ###Log: Video metadata
  logMessage <- data.frame(date = as.Date(today()), 
                           milestone = 5,
                           exit_code = NA,
                           note = "Composing FFMPEG strings")

  dbWriteTable(marsDBCon, DBI::SQL("log.tbl_script_video"), logMessage, append = TRUE, row.names=FALSE)

  final_mp4 <- mutate(check_mp4, ffmpeg_command = NA, filename = NA, dirname = NA)
  final_mov <- mutate(check_mov, ffmpeg_command = NA, filename = NA, dirname = NA)

  for(i in 1:nrow(check_mp4)){
      ffmpeg_stub <- NULL
      ffmpeg_infile <- NULL
      ffmpeg_framerate <- NULL
      ffmpeg_bitrate <- NULL
      
      #Are we running ffmpeg at all?
      if(check_mp4$convert[i] == TRUE){
        #We need to play with the path names so as to not exceed the maximum path length
        hostfolder <- dirname(check_mp4$filepath[i])
        
        
        ffmpeg_stub <- "ffmpeg -y "
        
        ffmpeg_infile <- paste0("x:", basename(check_mp4$filepath[i])) %>% shQuote
        ffmpeg_outfile <- str_replace(ffmpeg_infile, pattern = "\\.mp4", replacement = "_compressed.mp4")
        
        final_mp4$dirname[i] <- hostfolder

      } else{
        next
      }
      
      #Are we changing the frame rate?
      if(check_mp4$resample[i] == TRUE){
        ffmpeg_framerate <- paste0("-r ", targetFramerate)
      }
      
      #Are we changing the bit rate?
      if(check_mp4$compress[i] == TRUE){
        ffmpeg_bitrate <- paste0("-b:v 5M") #Set bit rate to 5 megabits per second
      }
      
      ffmpeg_string <- paste(ffmpeg_stub, '-i', ffmpeg_infile, ffmpeg_framerate, ffmpeg_bitrate, "-movflags +faststart", ffmpeg_outfile)
      final_mp4$ffmpeg_command[i] <- ffmpeg_string
  }  
  
  for(i in 1:nrow(check_mov)){
      ffmpeg_stub <- NULL
      ffmpeg_infile <- NULL
      ffmpeg_framerate <- NULL
      ffmpeg_bitrate <- NULL
      
      #Are we running ffmpeg at all?
      if(check_mov$convert[i] == TRUE){
        #We need to play with the path names so as to not exceed the maximum path length
        hostfolder <- dirname(check_mov$filepath[i])
        
        
        ffmpeg_stub <- "ffmpeg -y "
        
        ffmpeg_infile <- paste0("x:", basename(check_mov$filepath[i])) %>% shQuote
        ffmpeg_outfile <- str_replace(ffmpeg_infile, pattern = "\\.mov", replacement = "_compressed.mp4")
        
        final_mov$dirname[i] <- hostfolder

      } else{
        next
      }
      
      #Are we changing the frame rate?
      if(check_mov$resample[i] == TRUE){
        ffmpeg_framerate <- paste0("-r ", targetFramerate)
      }
      
      #Are we changing the bit rate?
      if(check_mov$compress[i] == TRUE){
        ffmpeg_bitrate <- paste0("-b:v 5M") #Set bit rate to 5 megabits per second
      }
      
      ffmpeg_string <- paste(ffmpeg_stub, '-i', ffmpeg_infile, ffmpeg_framerate, ffmpeg_bitrate, "-movflags +faststart", ffmpeg_outfile)
      final_mov$ffmpeg_command[i] <- ffmpeg_string
  }
```

```{r Section 5 - Compression}
  ###Log: Video metadata
  logMessage <- data.frame(date = as.Date(today()), 
                           milestone = 6,
                           exit_code = NA,
                           note = "Comperessing files")

  dbWriteTable(marsDBCon, DBI::SQL("log.tbl_script_video"), logMessage, append = TRUE, row.names=FALSE)
  
  results_mp4 <- list()
  for(i in 1:nrow(final_mp4)){
    if(final_mp4$convert[i] == FALSE){
      print(paste("Skipping:", final_mp4$filepath[i]))
      next
    } else{
      print(paste("Compressing:", final_mp4$filepath[i]))
      
      drive_command <- paste0("subst x: \"", final_mp4$dirname[i], "\"")
      print(drive_command)
      system(command = drive_command, intern = TRUE)
    
      print(final_mp4$ffmpeg_command[i])
      system(command = final_mp4$ffmpeg_command[i], intern = TRUE)
      
      undo_command <- "subst x: /D"
      print(undo_command)
      system(command = undo_command, intern = TRUE)
    }

  }

  results_mov <- list()
  for(i in 1:nrow(final_mov)){
    if(final_mov$convert[i] == FALSE){
      print(paste("Skipping:", final_mov$filepath[i]))
      next
    } else{
      print(paste("Compressing:", final_mov$filepath[i]))
      
      drive_command <- paste0("subst x: \"", final_mov$dirname[i], "\"")
      print(drive_command)
      system(command = drive_command, intern = TRUE)
    
      print(final_mov$ffmpeg_command[i])
      system(command = final_mov$ffmpeg_command[i], intern = TRUE)
      
      undo_command <- "subst x: /D"
      print(undo_command)
      system(command = undo_command, intern = TRUE)
    }

  }

```

```{r Section 4 - Close DB connections and render this file, include = FALSE} 

  ###Log: End
  logMessage <- data.frame(date = as.Date(today()), 
                           milestone = NA,
                           exit_code = errorCode,
                           note = errorCodes$message[errorCode+1])
  
  dbWriteTable(marsDBCon, DBI::SQL("log.tbl_script_video"), logMessage, append = TRUE, row.names=FALSE)
  
#Close database connections 
dbDisconnect(marsDBCon)
```