---
title: "Maintenance Script Report: Update Rainfall Tables"
author:
- Taylor Heffernan and Nick Manna
- Updating rainfall_gage
date: "`r lubridate::now()`" #This doesn't use !r syntax (like the gagedb param below) because it's not a param. It's evaluated by default.
output: html_document
params:
  database: "mars14_datav2" 
---

```{r setup, include=FALSE}
#Database Stuff
library(odbc)
library(tidyverse)
library(lubridate)
library(pwdgsi)
library(sf)
library(padr)

#Other stuff
library(knitr)
library(digest)
options(stringsAsFactors=FALSE)


errorCodes <- data.frame(code = 0:6,
  message = c("Execution successful.",
              "Could not connect to MARS and/or CentralDB. Are they down?",
              NA, #Write error from TryCatch will be used,
              NA, #Write error from TryCatch will be used,
              NA, #Write error from TryCatch will be used
              NA, #Write error from TryCatch will be used
              NA)
            , stringsAsFactors=FALSE)

kill = FALSE
errorCode = 0

logCode <- digest(now()) #Unique ID for the log batches

```

```{r Section 0 - Preamble and database connections, include=FALSE}
###Section 0.1: Check parameter validity

###Section 0.2: Connect to the database
	marsDBCon <- tryCatch({dbConnect(odbc::odbc(), params$database)},
                         error = function(e){e})

  hhdbcon <- tryCatch({dbConnect(odbc::odbc(), "CentralDB")},
                       error = function(e){e})

  #################################
  ####Error check - Did we connect?
  #################################
  if(any(typeof(marsDBCon) == "list", typeof(hhdbcon) == "list"))
  {
    kill = TRUE
    errorCode = 1
  }
  
    ###Log: Start
  logMessage <- data.frame(date = as.Date(today()), hash = logCode,
                           milestone = 1,
                           exit_code = NA,
                           note = "Testing DB connections")
  
  dbWriteTable(marsDBCon, DBI::SQL("log.tbl_script_rainfall"), logMessage, append = TRUE, row.names=FALSE)
	
```

```{r Break Point 1 - Connection Failure, echo = FALSE, include = TRUE, eval = kill}

  knitr::asis_output("# Script Results: Error\n")
  knitr::asis_output(paste("## Error Code:", errorCode, "\n"))
  knitr::asis_output(paste("## Error Message: ", errorCodes$message[errorCode+1]))

  ###Log: End
  logMessage <- data.frame(date = as.Date(today()), hash = logCode,
                           milestone = NA,
                           exit_code = errorCode,
                           note = errorCodes$message[errorCode+1])
  
  dbWriteTable(marsDBCon, DBI::SQL("log.tbl_script_rainfall"), logMessage, append = TRUE, row.names=FALSE)
  
  knitr::knit_exit()

```

```{r Section 1 - Gathering rainfall data, include = FALSE}

  ###Log: Start
  logMessage <- data.frame(date = as.Date(today()), hash = logCode,
                           milestone = 2,
                           exit_code = NA,
                           note = "Gathering Gage Data")
  
  dbWriteTable(marsDBCon, DBI::SQL("log.tbl_script_rainfall"), logMessage, append = TRUE, row.names=FALSE)
  
  
  #Read the rain gage data from the mars database
  rainfall_gage <- dbGetQuery(marsDBCon, "SELECT * from data.viw_gage_rain_latestdates")  
  
  #Read the rain gage table from the mars database and attach it to the rainfall data
  gage <- dbGetQuery(marsDBCon, "SELECT * FROM admin.tbl_gage")
  rainfall_gage <- right_join(rainfall_gage, gage, by = "gage_uid") %>% 
    transmute(gagename, 
              maxtime_edt = force_tz(coalesce(maxtime_edt, ymd("1900-01-01")), "America/New_York")) 
  #If we have no events (following a purge) we need a base date
    
  
  #Read the rain gage data from the H&H database
  hhrainfall_gage <- dbGetQuery(hhdbcon, "select * from pwdrg.tblModelRain") %>% 
    transmute(gagename = as.character(GaugeNo), 
              dtime_edt = force_tz(ymd_hms(DateTime), "America/New_York"), 
              rainfall_in = round(Rainfall, 4)) %>%
    filter(!is.na(dtime_edt))
  
  newgagedata <- hhrainfall_gage %>% 
    left_join(rainfall_gage, by = "gagename") %>% 
    group_by(gagename) %>%
    filter(dtime_edt > maxtime_edt) %>%
    ungroup %>%
    select(gagename, dtime_edt, rainfall_in) %>%
    left_join(gage, by = "gagename") %>%
    select(gage_uid, dtime_edt, rainfall_in) %>%
    arrange(gage_uid, dtime_edt) %>%
    mutate(rainfall_in = round(rainfall_in, 4)) %>%
    mutate(dtime_edt = as.character(dtime_edt)) %>%
    mutate(key = paste(gage_uid, dtime_edt, sep = "_"), dupe = duplicated(key)) %>%
    filter(!dupe) %>%
    select(-key, -dupe)
  
  output_newgagedata <- group_by(newgagedata, gage_uid) %>%
    summarize(new_measurements = n(), 
              latest_date = max(dtime_edt))
  
```

```{r Section R1: New Gage Data Output, echo = FALSE, include = TRUE, eval = nrow(newgagedata) > 0}
    knitr::asis_output(paste("### New Rain Gage Data to add to `data.tbl_gage_rain`: ", nrow(output_newgagedata)))
  
    kable(output_newgagedata)
    
      ###Log: Start
  logMessage <- data.frame(date = as.Date(today()), hash = logCode,
                           milestone = 3,
                           exit_code = NA,
                           note = "Writing Gage Data")
  
  dbWriteTable(marsDBCon, DBI::SQL("log.tbl_script_rainfall"), logMessage, append = TRUE, row.names=FALSE)
  
    tryCatch(
  
        expr = {
          dbWriteTable(marsDBCon, DBI::SQL("data.tbl_gage_rain"), newgagedata, append= TRUE, row.names = FALSE)
          success <<- TRUE
          },
        error = function(e) {
          kill <<- TRUE
          errorCode <<- 2
          errorCodes$message[errorCode+1] <<- e$message #Error object is a list
        }
      )
    #Writing file counts
    if(!kill){ #If the write succeeded
      logMessage <- data.frame(date = as.Date(today()),
                           records = nrow(newgagedata),
                           type = "Gage Records",
                           hash = logCode)
  
      dbWriteTable(marsDBCon, DBI::SQL("log.tbl_writes_rainfall"), logMessage, append = TRUE, row.names=FALSE)
    }


```

```{r Break Point 2 - Gage Write Failure, echo = FALSE, include = TRUE, eval = kill}

  knitr::asis_output("# Script Results: Error\n")
  knitr::asis_output(paste("## Error Code:", errorCode, "\n"))
  knitr::asis_output(paste("## Error Message: ", errorCodes$message[errorCode+1]))

  ###Log: End
  logMessage <- data.frame(date = as.Date(today()), hash = logCode,
                           milestone = NA,
                           exit_code = errorCode,
                           note = errorCodes$message[errorCode+1])
  
  dbWriteTable(marsDBCon, DBI::SQL("log.tbl_script_rainfall"), logMessage, append = TRUE, row.names=FALSE)
  
  knitr::knit_exit()

```

```{r Section 2 - Processing new rain events, include = FALSE}
  ###Log: Start
  logMessage <- data.frame(date = as.Date(today()), hash = logCode,
                           milestone = 4,
                           exit_code = NA,
                           note = "Processing Gage Events")
  
  dbWriteTable(marsDBCon, DBI::SQL("log.tbl_script_rainfall"), logMessage, append = TRUE, row.names=FALSE)

  #Read the rain gage data from the mars database
  #This query will grab all data from after the end of the latest event for each gage
  #This captures both new data appended in the previous section, and any data that was clipped last time events were processed
  newrain_query <- "select rg.gage_uid, rg.dtime_edt, rg.rainfall_in from data.tbl_gage_rain rg left join data.viw_gage_event_latestdates rgel on rg.gage_uid = rgel.gage_uid where rg.dtime_edt > rgel.dtime_edt"
  rain_newdata <- dbGetQuery(marsDBCon, newrain_query)
  
  #If there's no defined rain events, that query will return nothing
  #So we need to grab the entire data set
  emptytable <- dbGetQuery(marsDBCon, "select count(*) from data.viw_gage_event_latestdates") %>% pull(count)
  if(emptytable == 0){
    rain_newdata <- dbGetQuery(marsDBCon, "select dtime_edt, gage_uid, rainfall_in from data.tbl_gage_rain order by gage_uid, dtime_edt asc")
  }
  
  #Process the rain data into events, based on a 6 hour interevent time and a minimum depth of 0.1 inches
  rain_newevents <- rain_newdata %>% 
    group_by(gage_uid) %>%
    arrange(dtime_edt) %>% 
    mutate(event_id = marsDetectEvents(dtime_edt, rainfall_in)) %>%
      #Drop the last "complete" event in case it straddles the month boundary
      #It will get processed the when the next batch of data comes in
    filter(!is.na(event_id), event_id != max(event_id, na.rm = TRUE)) %>%
    group_by(gage_uid, event_id) %>%
    summarize(eventdatastart_edt = first(dtime_edt),
      eventdataend_edt = last(dtime_edt),
      eventduration_hr = marsStormDuration_hr(dtime_edt),
      eventpeakintensity_inhr = marsStormPeakIntensity_inhr(dtime_edt, rainfall_in),
      eventavgintensity_inhr = marsStormAverageIntensity_inhr(dtime_edt, rainfall_in),
      eventdepth_in = marsStormDepth_in(rainfall_in)) %>%
    select(-event_id)
  
  rain_newevents <- mutate(rain_newevents, 
                           eventdatastart_edt = as.character(eventdatastart_edt),
                           eventdataend_edt = as.character(eventdataend_edt))
```

```{r Section R2: New Gage Event Output, echo = FALSE, include = TRUE, eval = nrow(rain_newevents) > 0}
    knitr::asis_output(paste("### New Rain Gage events to add to `data.tbl_gage_rain_event`: ", nrow(rain_newevents)))
  
      ###Log: Start
  logMessage <- data.frame(date = as.Date(today()), hash = logCode,
                           milestone = 5,
                           exit_code = NA,
                           note = "Writing Gage Events")
  
  dbWriteTable(marsDBCon, DBI::SQL("log.tbl_script_rainfall"), logMessage, append = TRUE, row.names=FALSE)
    
  
    tryCatch(
  
        expr = {
          dbWriteTable(marsDBCon, DBI::SQL("data.tbl_gage_event"), rain_newevents, append= TRUE, row.names = FALSE)
          success <<- TRUE
          },
        error = function(e) {
          kill <<- TRUE
          errorCode <<- 3
          errorCodes$message[errorCode+1] <<- e$message #Error object is a list
        }
      )
  
    if(!kill){ #If the write succeeded
      logMessage <- data.frame(date = as.Date(today()),
                           records = nrow(rain_newevents),
                           type = "Gage Events",
                           hash = logCode)
  
      dbWriteTable(marsDBCon, DBI::SQL("log.tbl_writes_rainfall"), logMessage, append = TRUE, row.names=FALSE)
    }


```

```{r Break Point 3 - Gage Data Write Failure, echo = FALSE, include = TRUE, eval = kill}

  knitr::asis_output("# Script Results: Error\n")
  knitr::asis_output(paste("## Error Code:", errorCode, "\n"))
  knitr::asis_output(paste("## Error Message: ", errorCodes$message[errorCode+1]))
  
  ###Log: End
  logMessage <- data.frame(date = as.Date(today()), hash = logCode,
                           milestone = NA,
                           exit_code = errorCode,
                           note = errorCodes$message[errorCode+1])
  
  dbWriteTable(marsDBCon, DBI::SQL("log.tbl_script_rainfall"), logMessage, append = TRUE, row.names=FALSE)  
  
  knitr::knit_exit()

```

```{r Section 3 - Gathering radar data, include = FALSE}
  ###Log: Start
  logMessage <- data.frame(date = as.Date(today()), hash = logCode,
                           milestone = 6,
                           exit_code = NA,
                           note = "Gathering Radar Data")
  
  dbWriteTable(marsDBCon, DBI::SQL("log.tbl_script_rainfall"), logMessage, append = TRUE, row.names=FALSE)  

  #Assess raw files in our DB and H&H
  db_rawfiles <- dbGetQuery(marsDBCon, "select * from admin.tbl_radar_rawfile")
  hh_rawfiles <- dbGetQuery(hhdbcon, "select yearmon, path as filepath from radar2sheds.garr_inventory") %>%
    mutate(yearmon = str_replace(yearmon, "-", "")) %>%
    filter(yearmon > "201401") %>%
    mutate(filepath = str_replace(filepath, "M:\\\\", "//pwdoows/OOWS/Modeling/")) %>% #Replace the drive letter
    mutate(filepath = str_replace(filepath, "M:/", "//pwdoows/OOWS/Modeling/")) %>% #Newer file paths are formatted differently
    mutate(filepath = str_replace(filepath, "\\\\", "/")) %>% #Replace the generic \ with / for path separation
    mutate(filepath = str_replace(filepath, "bases\\\\", "bases/")) %>% #This one doesn't match in the above regex, somehow
    mutate(filepath = str_replace(filepath, "fall\\\\", "fall/")) #Neither does this one
  dbDisconnect(hhdbcon)

  #Which files don't we have
  new_rawfiles <- filter(hh_rawfiles, !(filepath %in% db_rawfiles$filepath)) 
  
  #only cells in Philly
  phillycells <- dbGetQuery(marsDBCon, "select radar_uid from admin.tbl_radar")
  
  #Unzip the files
  dir.create("~/radarrain", showWarnings = FALSE)
  for(i in 1:nrow(new_rawfiles)){
    if(nrow(new_rawfiles) == 0){break}
    file.copy(from = new_rawfiles$filepath[i], to = "~/radarrain", overwrite = FALSE)
    unzip(paste0("~/radarrain/", basename(new_rawfiles$filepath[i])), exdir = "~/radarrain", files = paste0(new_rawfiles$yearmon[i], ".csv"))
    file.remove(paste0("~/radarrain/", basename(new_rawfiles$filepath[i])))
  }
  
  #read the files
  newradarfiles <- list.files(path = "~/radarrain", full.names = TRUE, pattern = "\\.csv$")
  newradardata <- data.frame(dtime_edt = NULL, radar_uid = NULL, rainfall_in = NULL)
  for(i in 1:length(newradarfiles)){
    if(length(newradarfiles) == 0){break}
    print(paste0("reading ", newradarfiles[i]))
    radarfile <- read.csv(newradarfiles[i], header = FALSE)
    colnames(radarfile) <- c("dtime_raw", "tz", "radar_uid", "rainfall_in")
    radarfile <- radarfile %>% 
      filter(radar_uid %in% phillycells$radar_uid) %>%
      transmute(dtime_edt = ymd_hm(dtime_raw, tz = "America/New_York"), radar_uid, rainfall_in)
   
    radarinterval <- get_interval(radarfile$dtime_edt)
    print(paste("File", basename(newradarfiles[i]), "has datetime interval", radarinterval))
  
    if(radarinterval != "15 min"){
      radarfile <- thicken(radarfile, "15 min", rounding = "up", ties_to_earlier = TRUE) %>%
        group_by(dtime_edt_15_min, radar_uid) %>%
        summarize(rainfall_in = sum(rainfall_in)) %>%
        select(dtime_edt = dtime_edt_15_min, radar_uid, rainfall_in)
    }

    radarfile <- filter(radarfile, rainfall_in > 0)
       
    newradardata <- bind_rows(newradardata, radarfile)
    file.remove(newradarfiles[i])
  }
  
  if(nrow(newradardata) > 0){
     newradardata <- mutate(newradardata, rainfall_in = as.character(rainfall_in))
  }
  
```

```{r Section R3: New Radar Data Output, echo = FALSE, include = TRUE, eval = nrow(newradardata) > 0}
    knitr::asis_output(paste("### New Radar data to add to `data.tbl_radar_rain_event`: ", nrow(newradardata)))
  
    kable(new_rawfiles)
    
      ###Log: Start
  logMessage <- data.frame(date = as.Date(today()), hash = logCode,
                           milestone = 7,
                           exit_code = NA,
                           note = "Writing Radar Data")
  
  dbWriteTable(marsDBCon, DBI::SQL("log.tbl_script_rainfall"), logMessage, append = TRUE, row.names=FALSE)
  
    tryCatch(
  
        expr = {
          dbWriteTable(marsDBCon, DBI::SQL("admin.tbl_radar_rawfile"), new_rawfiles, append= TRUE, row.names = FALSE)
          success <<- TRUE
          },
        error = function(e) {
          kill <<- TRUE
          errorCode <<- 4
          errorCodes$message[errorCode+1] <<- e$message #Error object is a list
        }
      )
  
    if(!kill){ #If the write succeeded
      logMessage <- data.frame(date = as.Date(today()),
                           records = nrow(new_rawfiles),
                           type = "Radar Files",
                           hash = logCode)
  
      dbWriteTable(marsDBCon, DBI::SQL("log.tbl_writes_rainfall"), logMessage, append = TRUE, row.names=FALSE)
    }
    
    tryCatch(
  
        expr = {
          dbWriteTable(marsDBCon, DBI::SQL("data.tbl_radar_rain"), newradardata, append= TRUE, row.names = FALSE)
          success <<- TRUE
          },
        error = function(e) {
          kill <<- TRUE
          errorCode <<- 5
          errorCodes$message[errorCode+1] <<- e$message #Error object is a list
        }
      )

    if(!kill){ #If the write succeeded
      logMessage <- data.frame(date = as.Date(today()),
                           records = nrow(newradardata),
                           type = "Radar Records",
                           hash = logCode)
  
      dbWriteTable(marsDBCon, DBI::SQL("log.tbl_writes_rainfall"), logMessage, append = TRUE, row.names=FALSE)
    }

```

```{r Break Point 4 - Radar Data Write Failure, echo = FALSE, include = TRUE, eval = kill}

  knitr::asis_output("# Script Results: Error\n")
  knitr::asis_output(paste("## Error Code:", errorCode, "\n"))
  knitr::asis_output(paste("## Error Message: ", errorCodes$message[errorCode+1]))

  ###Log: End
  logMessage <- data.frame(date = as.Date(today()), hash = logCode,
                           milestone = NA,
                           exit_code = errorCode,
                           note = errorCodes$message[errorCode+1])
  
  dbWriteTable(marsDBCon, DBI::SQL("log.tbl_script_rainfall"), logMessage, append = TRUE, row.names=FALSE)
  
  knitr::knit_exit()

```

```{r Section 4 - Processing new rain events for radar data, include = FALSE}
  ###Log: Start
  logMessage <- data.frame(date = as.Date(today()), hash = logCode,
                           milestone = 8,
                           exit_code = NA,
                           note = "Processing Radar Events")
  
  dbWriteTable(marsDBCon, DBI::SQL("log.tbl_script_rainfall"), logMessage, append = TRUE, row.names=FALSE)

  #Read the radar data from the mars database
  #This query will grab all data from after the end of the latest event for each cell
  #This captures both new data appended in the previous section, and any data that was clipped last time events were processed

  #process cells one at a time
  allcells <- dbGetQuery(marsDBCon, "select distinct radar_uid from admin.tbl_radar")

  newrain_query <- paste("select rc.radar_uid, rc.dtime_edt, rc.rainfall_in from data.tbl_radar_rain rc left join data.viw_radar_event_latestdates rcel on rc.radar_uid = rcel.radar_uid where rc.dtime_edt > rcel.dtime_edt")

    
  rain_newdata <- dbGetQuery(marsDBCon, newrain_query)  
    
  print(paste(nrow(rain_newdata), "data points"))
    
    #Process the rain data into events, based on a 6 hour interevent time and a minimum depth of 0.1 inches
    rain_newevents <- rain_newdata %>% 
      group_by(radar_uid) %>%
      arrange(dtime_edt) %>% 
      mutate(event_id = marsDetectEvents(dtime_edt, rainfall_in)) %>%
      #Drop the last "complete" event in case it straddles the month boundary
      #It will get processed the when the next batch of data comes in
      filter(!is.na(event_id), event_id != max(event_id, na.rm = TRUE)) %>%
      group_by(radar_uid, event_id) %>%
      summarize(eventdatastart_edt = first(dtime_edt),
                eventdataend_edt = last(dtime_edt),
                eventduration_hr = marsStormDuration_hr(dtime_edt),
                eventpeakintensity_inhr = marsStormPeakIntensity_inhr(dtime_edt, rainfall_in),
                eventavgintensity_inhr = marsStormAverageIntensity_inhr(dtime_edt, rainfall_in),
                eventdepth_in = marsStormDepth_in(rainfall_in)) %>% 
      select(-event_id)
      
      print(paste(nrow(rain_newevents), "new events"))
    
  
```

```{r Section R4: New Radar Event Output, echo = FALSE, include = TRUE, eval = nrow(rain_newevents) > 0}
    knitr::asis_output(paste("### New Rain Radar events to add to `data.tbl_radar_rain_event`: ", nrow(rain_newevents)))
  
    kable(rain_newevents)
    
      ###Log: Start
  logMessage <- data.frame(date = as.Date(today()), hash = logCode,
                           milestone = 9,
                           exit_code = NA,
                           note = "Writing Radar Events")
  
  dbWriteTable(marsDBCon, DBI::SQL("log.tbl_script_rainfall"), logMessage, append = TRUE, row.names=FALSE)
  
    tryCatch(
  
        expr = {
          dbWriteTable(marsDBCon, DBI::SQL("data.tbl_radar_event"), rain_newevents, append= TRUE, row.names = FALSE)
          success <<- TRUE
          },
        error = function(e) {
          kill <<- TRUE
          errorCode <<- 6
          errorCodes$message[errorCode+1] <<- e$message #Error object is a list
        }
      )

    if(!kill){ #If the write succeeded
      logMessage <- data.frame(date = as.Date(today()),
                           records = nrow(rain_newevents),
                           type = "Radar Records",
                           hash = logCode)
  
      dbWriteTable(marsDBCon, DBI::SQL("log.tbl_writes_rainfall"), logMessage, append = TRUE, row.names=FALSE)
    }

```

```{r Break Point 5 - Radar Event Write Failure, echo = FALSE, include = TRUE, eval = kill}

  knitr::asis_output("# Script Results: Error\n")
  knitr::asis_output(paste("## Error Code:", errorCode, "\n"))
  knitr::asis_output(paste("## Error Message: ", errorCodes$message[errorCode+1]))

  ###Log: End
  logMessage <- data.frame(date = as.Date(today()), hash = logCode,
                           milestone = NA,
                           exit_code = errorCode,
                           note = errorCodes$message[errorCode+1])
  
  dbWriteTable(marsDBCon, DBI::SQL("log.tbl_script_rainfall"), logMessage, append = TRUE, row.names=FALSE)
  
  knitr::knit_exit()

```

# Script Results: SUCCESS
## Exit Code: `r errorCode`
## Exit Message: `r errorCodes$message[errorCode+1]`

```{r Section 3 - Close DB connections and render this file, include = FALSE}
	#Close database connections

  ###Log: End
  logMessage <- data.frame(date = as.Date(today()), hash = logCode,
                           milestone = NA,
                           exit_code = errorCode,
                           note = errorCodes$message[errorCode+1])
  
  dbWriteTable(marsDBCon, DBI::SQL("log.tbl_script_rainfall"), logMessage, append = TRUE, row.names=FALSE)

	dbDisconnect(marsDBCon)
```