---
title: "Worker Script: Update Plan Review Tables"
author: "Taylor Heffernan, Brian Cruice"
date: "07/29/2024"
output: html_document
params:
  database: "mars14_datav2" #Requires a DSN of the same name
---

```{r Section 0.1 Setup and DB connections, include=FALSE}

#database packages
library(odbc)

#data manipulation packages
library(tidyverse)

#hashing packages
library(digest)

errorCodes <- data.frame(code = 0:4,
  message = c("Execution successful.",
              "Could not connect to DBs. Is Postgres down?",
              "Query Failure.",
              NA, #Write error from TryCatch will be used
              NA #Write error from TryCatch will be used
               ), stringsAsFactors=FALSE)

kill = FALSE
errorCode = 0

log_code <- digest(now()) #Unique ID for the log batches

#db connections 

mars_data <- dbConnect(odbc(), params$database)

###Log: Start
logMessage <- data.frame(date = as.Date(today()), hash = log_code,
                         milestone = 1,
                         exit_code = NA,
                         note = "Testing DB Connection")

dbWriteTable(mars_data, RPostgres::Id(schema = "log", table = "tbl_script_planreview"), logMessage, append = TRUE, row.names=FALSE)

planreview <- dbConnect(odbc(), 
                        Driver = "ODBC Driver 17 for SQL Server", 
                        Server = "PWDSPRA", 
                        Database = "SPRA_ReportingDB", 
                        port = 1433,
                        uid = Sys.getenv("gis_uid"),
                        pwd= Sys.getenv("gis_pwd"))



  #################################
  ####Error check - Did we connect?
  #################################
  if(any(!odbc::dbIsValid(mars_data), !odbc::dbIsValid(planreview)))
  {
    kill = TRUE
    errorCode = 1
  }
```

```{r Break Point 1 - Bad Connection, echo = FALSE, eval = kill}

  knitr::asis_output("# Script Results: Error\n")
  knitr::asis_output(paste("## Error Code:", errorCode, "\n"))
  knitr::asis_output(paste("## Error Message: ", errorCodes$message[errorCode+1]))
  
  ###Log: End
  logMessage <- data.frame(date = as.Date(today()), hash = log_code,
                           milestone = NA,
                           exit_code = errorCode,
                           note = errorCodes$message[errorCode+1])
  
  dbWriteTable(mars_data, RPostgres::Id(schema = "log", table = "tbl_script_planreview"), logMessage, append = TRUE, row.names=FALSE)
  
  knitr::knit_exit()

```

```{r Section 1: Querrying and Hashing, echo=FALSE}

  ###Log: Start
  logMessage <- data.frame(date = as.Date(today()), hash = log_code,
                           milestone = 2,
                           exit_code = NA,
                           note = "Querying new data")
  
  dbWriteTable(mars_data, RPostgres::Id(schema = "log", table = "tbl_script_planreview"), logMessage, append = TRUE, row.names=FALSE)

#Query plan review tables

      tryCatch({view_smp_designation <- dbGetQuery(planreview, "select p.spra_legacyprojectid as \"ProjectID\", s.spra_name as \"SMPID\", p.spra_projectname as \"Projectname\", p.spra_trackingid as \"TrackingNumber\",
	d.Designation as \"Designation\", p.spra_smipfundedname as \"SMIP\", p.spra_garpfundedname as \"GARP\",
	pt.spra_oowprogramtype as \"OOWProgramType\"
from spra_project p inner join 
	(select * from spra_projectsmpdetails s where s.spra_smptypename <> 'Site Characteristics') s
		on p.spra_trackingid = s.spra_projectname
	inner join View_Project_Designation d on p.spra_trackingid = d.TrackingNumber
	left join spra_programtype pt on p.spra_programtypes = pt.spra_programtypeid
order by p.spra_trackingid, s.spra_name")
        }, # append the data
        error = function(e){
          kill <<- TRUE
          errorCode <<- 2
          errorCodes$message[errorCode+1] <<- e$message #Error object is a list
          success <<- TRUE
        }
      )
  
   tryCatch({head_vals <- dbGetQuery(planreview, "select spra_name as 'smp_id',
                                                  spra_smptypename as 'smp_type',
                                                  coalesce(spra_depthofmedium_asmaintained, spra_depthofmedium_asbuilt,
                                                    spra_depthofmedium_approved) as 'medium_depth_ft',
                                                  coalesce(spra_effectivehead_asmaintained, spra_effectivehead_asbuilt,
                                                    spra_effectivehead_approved) as 'effective_head_ft',
                                                  coalesce(spra_stonestoragedepth_asmaintained/12, spra_stonestoragedepth_asbuilt/12, 
                                                    spra_stonestoragedepth_approved/12) as 'stone_storage_depth_ft',
                                                  coalesce(spra_footprint_asmaintained, spra_footprint_asbuilt, spra_footprint_approved)
                                                    as 'footprint_ft2',
                                                  coalesce(spra_staticstorage_asmaintained, spra_staticstorage_asbuilt,
                                                    spra_staticstorage_approved) as 'static_storage_vol_ft3',
                                                  coalesce(spra_waterqualityvolume_asmaintained, spra_waterqualityvolume_asbuilt,
                                                    spra_waterqualityvolume_approved) as 'water_quality_vol_ft3',
                                                  coalesce(spra_orificediameter_asmaintained, spra_orificediameter_asbuilt,                                                                 spra_orificediameter_approved) as 'orifice_diameter_in',                                                                              coalesce(spra_testinfiltrationrate_asmaintained, spra_testinfiltrationrate_asbuilt,                                                       spra_testinfiltrationrate_approved) as 'infil_dsg_rate_inhr'
                                                  from spra_projectsmpdetails s")  %>% 
              dplyr::mutate(water_quality_head_ft = water_quality_vol_ft3/footprint_ft2) %>%
              dplyr::mutate(static_storage_head_ft = static_storage_vol_ft3/footprint_ft2)  
    },
     error = function(e){
     kill <<- TRUE
     errorCode <<- 2
     errorCodes$message[errorCode+1] <<- e$message #Error object is a list
     success <<- TRUE
        }
    )
  
    tryCatch({planreview_crosstab <-dbGetQuery(planreview,
                              "select bv.SMPID as 'smp_id',
                                      bv.DCIA_best as 'dcia_ft2',
                                      bv.SlowReleaseVolume_best as 'slow_release_vol_ft3',
                                      coalesce(bv.SysType_AM,bv.SysType_AB,bv.SysType_AP) as 'system_type',
                                      coalesce(bv.Loca_AM, bv.Loca_AB, bv.Loca_AP) as 'location'
                               from View_SMP_BestValues bv")
    
    smip_garp_des <- view_smp_designation %>% dplyr::select(SMPID, SMIP, GARP)
    smip_garp_des <- smip_garp_des %>%
                        dplyr::mutate(smp_id = SMPID, smip = SMIP, garp = GARP) %>%
                        dplyr::select(-SMPID, -SMIP, -GARP)

    planreview_crosstab <- planreview_crosstab %>% dplyr::left_join(smip_garp_des, by = "smp_id")
    planreview_crosstab <- planreview_crosstab %>% dplyr::left_join(head_vals, by = "smp_id")
    
    },
     error = function(e){
     kill <<- TRUE
     errorCode <<- 2
     errorCodes$message[errorCode+1] <<- e$message #Error object is a list
     success <<- TRUE
        }
    )
  
  if(!kill)
  {
    #Hash plan view tables
    view_smp_designation_hash <- view_smp_designation %>% 
      rowwise() %>% 
      mutate("hash_md5" = digest(paste(`ProjectID`, `TrackingNumber`,  `SMPID`, `Designation`, `OOWProgramType`, `SMIP`, `GARP`), algo = "md5")) 
    
    planreview_crosstab_hash <- planreview_crosstab %>%
      rowwise() %>%
      mutate("hash_md5" = digest(paste(smp_id, dcia_ft2, slow_release_vol_ft3, system_type, smip, garp,
                                       smp_type, medium_depth_ft, effective_head_ft, stone_storage_depth_ft, footprint_ft2,
                                       static_storage_vol_ft3, water_quality_vol_ft3, water_quality_head_ft, static_storage_head_ft)))
  }



```

```{r Break Point 2 - Bad Read, echo = FALSE, eval = kill}

  knitr::asis_output("# Script Results: Error\n")
  knitr::asis_output(paste("## Error Code:", errorCode, "\n"))
  knitr::asis_output(paste("## Error Message: ", errorCodes$message[errorCode+1]))
  
  ###Log: End
  logMessage <- data.frame(date = as.Date(today()), hash = log_code,
                           milestone = NA,
                           exit_code = errorCode,
                           note = errorCodes$message[errorCode+1])
  
  dbWriteTable(mars_data, RPostgres::Id(schema = "log", table = "tbl_script_planreview"), logMessage, append = TRUE, row.names=FALSE)
  
  knitr::knit_exit()

```

```{r Section 2: Trimming, Joining, and Writing, echo = FALSE}

#Query existing table from MARS
mars_private <- dbGetQuery(mars_data, "select planreview_private_uid, \"SMPID\", hash_md5 from external.tbl_planreview_private")
mars_crosstab <- dbGetQuery(mars_data, "select planreview_crosstab_uid, smp_id, hash_md5 from external.tbl_planreview_crosstab")

#Trim existing table to just hashes

#New hashes
new_smp_hashes <- view_smp_designation_hash %>% 
  filter(!(SMPID %in% mars_private$SMPID))

new_crosstab_hashes <- planreview_crosstab_hash %>%
  filter(!(smp_id %in% mars_crosstab$smp_id))

#Updated metrics
updated_smps <- view_smp_designation_hash %>%
  filter(!(SMPID %in% new_smp_hashes$SMPID)) %>%
  anti_join(mars_private, by = "hash_md5")

updated_crosstab <- planreview_crosstab_hash %>%
  filter(!(smp_id %in% new_crosstab_hashes$smp_id)) %>%
  anti_join(mars_crosstab, by = "hash_md5")

#Append UIDs for update
  updated_uids <- select(mars_private, SMPID, planreview_private_uid)
  edited_smps <- left_join(updated_smps, updated_uids, by = "SMPID")
  
  updated_crosstab_uids <- select(mars_crosstab, smp_id, planreview_crosstab_uid)
  edited_crosstab_smps <- left_join(updated_crosstab, updated_crosstab_uids, by = "smp_id")

```

```{r Section R1: New SMP Output, echo = FALSE, include = TRUE, eval = all(!kill, any(nrow(new_smp_hashes) > 0, nrow(new_crosstab_hashes) > 0))}

  ###Log: Start
  logMessage <- data.frame(date = as.Date(today()), hash = log_code,
                           milestone = 3,
                           exit_code = NA,
                           note = "Writing new updates")
  
  dbWriteTable(mars_data, RPostgres::Id(schema = "log", table = "tbl_script_planreview"), logMessage, append = TRUE, row.names=FALSE)
  
#Write to mars_data
  
  #append new SMPs
      tryCatch(
  
        expr = {
          dbWriteTable(mars_data, RPostgres::Id(schema = "external", table = "tbl_planreview_private_fixed"), new_smp_hashes, append= TRUE, row.names = FALSE)
          success <<- TRUE
          },
        error = function(e) {
          kill <<- TRUE
          errorCode <<- 3
          errorCodes$message[errorCode+1] <<- e$message #Error object is a list
        }
      )
  
      tryCatch(
  
        expr = {
          dbWriteTable(mars_data, RPostgres::Id(schema = "external", table = "tbl_planreview_crosstab"), new_crosstab_hashes, append= TRUE, row.names = FALSE)
          success <<- TRUE
          },
        error = function(e) {
          kill <<- TRUE
          errorCode <<- 3
          errorCodes$message[errorCode+1] <<- e$message #Error object is a list
        }
      )

  if(!kill)
  {
    #Writing file counts
    logMessage <- data.frame(date = as.Date(today()),
                         records = nrow(new_smp_hashes),
                         type = "SMPs",
                         hash = log_code)

    dbWriteTable(mars_data, RPostgres::Id(schema = "log", table = "tbl_writes_planreview"), logMessage, append = TRUE, row.names=FALSE) 
  }
    
```

```{r Break Point 3 - Bad Write, echo = FALSE, eval = kill}

  knitr::asis_output("# Script Results: Error\n")
  knitr::asis_output(paste("## Error Code:", errorCode, "\n"))
  knitr::asis_output(paste("## Error Message: ", errorCodes$message[errorCode+1]))
  
  ###Log: End
  logMessage <- data.frame(date = as.Date(today()), hash = log_code,
                           milestone = NA,
                           exit_code = errorCode,
                           note = errorCodes$message[errorCode+1])
  
  dbWriteTable(mars_data, RPostgres::Id(schema = "log", table = "tbl_script_planreview"), logMessage, append = TRUE, row.names=FALSE)
  
  knitr::knit_exit()

```

```{r Section R2: New Edits Output, echo = FALSE, include = TRUE, eval = all(!kill, any(nrow(edited_smps) > 0))}

  ###Log: Start
  logMessage <- data.frame(date = as.Date(today()), hash = log_code,
                           milestone = 4,
                           exit_code = NA,
                           note = "Writing new edits")
  
  dbWriteTable(mars_data, RPostgres::Id(schema = "log", table = "tbl_script_planreview"), logMessage, append = TRUE, row.names=FALSE)
  
#Write to mars_data
  
  #write update query-----
        tryCatch(
  
        expr = {
          update_smp <- dbSendQuery(mars_data, 'update external.tbl_planreview_private set \"ProjectID\"=?, \"SMPID\"=?, \"Projectname\" =  ?, \"TrackingNumber\"=?, \"Designation\"=?, \"SMIP\"=?, \"GARP\"=?, \"OOWProgramType\"=?, hash_md5=? WHERE planreview_private_uid=?')

          #send the updated data
          dbBind(update_smp, edited_smps)
          
          #release the prepared statement
          dbClearResult(update_smp)
          success <<- TRUE
          },
        error = function(e) {
          kill <<- TRUE
          errorCode <<- 3
          errorCodes$message[errorCode+1] <<- e$message #Error object is a list
        }
      )
        tryCatch(
  
        expr = {
          update_crosstab <- dbSendQuery(mars_data, 'update external.tbl_planreview_private set smp_id= ?, dcia_ft2= ?, slow_release_vol_ft3 =  ?, system_type=?,            smip= ?, garp= ?, smp_type= ?, medium_depth_ft= ?, effective_head_ft= ?, stone_storage_depth_ft=?, footprint_ft2, static_storage_vol_ft3= ?,
                                         water_quality_vol_ft3= ?, water_quality_head_ft= ?,static_storage_head_ft= ?, hash_md5= ?
                                         WHERE planreview_crosstab_uid = ?')

          #send the updated data
          dbBind(updated_crosstab, edited_crosstab_smps)
          
          #release the prepared statement
          dbClearResult(updated_crosstab)
          success <<- TRUE
          },
        error = function(e) {
          kill <<- TRUE
          errorCode <<- 3
          errorCodes$message[errorCode+1] <<- e$message #Error object is a list
        }
      )
  
  if(!kill)
  {
    #Writing file counts
    logMessage <- data.frame(date = as.Date(today()),
                         records = nrow(edited_smps),
                         type = "Updates",
                         hash = log_code)

    dbWriteTable(mars_data, RPostgres::Id(schema = "log", table = "tbl_writes_planreview"), logMessage, append = TRUE, row.names=FALSE) 
  }
  
  
```

```{r Break Point 4 - Bad Update, echo = FALSE, eval = kill}

  knitr::asis_output("# Script Results: Error\n")
  knitr::asis_output(paste("## Error Code:", errorCode, "\n"))
  knitr::asis_output(paste("## Error Message: ", errorCodes$message[errorCode+1]))
  
  ###Log: End
  logMessage <- data.frame(date = as.Date(today()), hash = log_code,
                           milestone = NA,
                           exit_code = errorCode,
                           note = errorCodes$message[errorCode+1])
  
  dbWriteTable(mars_data, RPostgres::Id(schema = "log", table = "tbl_script_planreview"), logMessage, append = TRUE, row.names=FALSE)
  
  knitr::knit_exit()

```

```{r Section3: Clean Up Connections and Render This HTML Document, echo = FALSE}

  knitr::asis_output("# Script Results: Success\n")
  knitr::asis_output(paste("## Error Code:", errorCode, "\n"))
  knitr::asis_output(paste("## Error Message: ", errorCodes$message[errorCode+1]))
  
  ###Log: End
  logMessage <- data.frame(date = as.Date(today()), hash = log_code,
                           milestone = NA,
                           exit_code = errorCode,
                           note = errorCodes$message[errorCode+1])
  
  dbWriteTable(mars_data, RPostgres::Id(schema = "log", table = "tbl_script_planreview"), logMessage, append = TRUE, row.names=FALSE)
  

dbDisconnect(planreview)
dbDisconnect(mars_data)

  knitr::knit_exit()


```
